export const productList = require('./productList.json');

const data = {
  carouselImg: [
    {
      id: 14422,
      url:
        'https://base-ec2if.akamaized.net/images/user/template/peaks8-official-ec/image-slider1_5ac33f367c2ef.jpg',
    },
    {
      id: 25125,
      url:
        'https://base-ec2if.akamaized.net/images/user/template/peaks8-official-ec/image-slider3_5ac4a8aa184d7.jpg',
    },
    {
      id: 2123,
      url:
        'https://base-ec2if.akamaized.net/images/user/template/peaks8-official-ec/image-slider5_5ac4a76cd0be8.jpg',
    },
    {
      id: 12354,
      url:
        'https://base-ec2if.akamaized.net/images/user/template/peaks8-official-ec/image-slider2_5ac33f36c6f3c.jpg',
    },
    {
      id: 5125,
      url:
        'https://base-ec2if.akamaized.net/images/user/template/peaks8-official-ec/image-slider4_5ac4aa0c080ff.jpg',
    },
  ],
  pickUpImg: [
    {
      url:
        'https://base-ec2if.akamaized.net/images/user/template/peaks8-official-ec/image-pick_img_1_5ac6ea2d6a80d.jpg',
    },
    {
      url:
        'https://base-ec2if.akamaized.net/images/user/template/peaks8-official-ec/image-pick_img_2_5ac6ea2db16b6.jpg',
    },
    {
      url:
        'https://base-ec2if.akamaized.net/images/user/template/peaks8-official-ec/image-pick_img_3_5ac6ea2e08c29.jpg',
    },
  ],
  newsInfo: [
    {
      priority: 41231,
      url: 'https://goo.gl/1cgBmE',
      headline:
        'AMAZON 1afffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
      date: '04/21/2018',
    },
    {
      priority: 552,
      url: 'https://goo.gl/1cgBmE',
      headline: 'AMAZON 2aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      date: '04/21/2018',
    },
    {
      priority: 34123,
      url: 'https://goo.gl/1cgBmE',
      headline: 'AMAZON 3ggggggggggggggggggggggggggggggggggggggggggggggg',
      date: '04/21/2018',
    },
    {
      priority: 341223,
      url: '',
      headline: 'AMAZON 3ggggggggggggggggggggggggggggggggggggggggggggggg',
      date: '04/21/2018',
    },
  ],
  productList: [
    {
      productImg:
        'https://base-ec2if.akamaized.net/w=300,a=0,q=90,u=1/images/item/origin/6f2ddb67572855eaac5ab4cc4fbac4e6.jpg',
      productId: 106611181,
      productCode: 'P818LSL01',
      productSamples: [
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
      ],
      productGender: 'women',
      productVariable: ['light blue', 'gray', 'olive', 'black'],
      productCategory: ['hoodie'],
      productDescription: {
        prefix: 'Water Absorbable Quick Drying UV',
        availability: 10,
        sizes: ['s', 'm', 'l'],
        sizeSpec: [
          {
            size: 's',
            measure: 'cm',
            spec:
              '[waist] 76.0 [hip] 103.0 [hem opening] 40.2 [pants length] 97.0 [inseam] 78.0',
          },
          {
            size: 'm',
            measure: 'cm',
            spec:
              '[waist] 80.0 [hip] 107.0 [ Hemp mouth] 41.0 [Pants Length] 101.0 [Inseam] 81.0',
          },
          {
            size: 'l',
            measure: 'cm',
            spec:
              '[Waist] 84.0 [Hip] 111.0 [Hemming Port] 41.8 [Pants Length] 105.0 [Inseam] 84.0 ',
          },
        ],
        info: [
          'Parker that can be UV-protected from the sun in summer',
          'Ultraviolet cut is the highest value UPF 50+',
          'Peaks Eight unique fabric is used',
          'Shaw Deodorant effect using yarn',
          'Simple design that since the time of commuting and going out not only the seaside',
        ],
      },
      productName: 'Hoodie',
      productPrice: 280000,
      listingDate: '04/21/2018',
      location: 'hcm',
    },
    {
      productImg:
        'https://base-ec2if.akamaized.net/w=300,a=0,q=90,u=1/images/item/origin/2c3246a771dca90ed78a57a9a8aeb595.jpg',
      productId: 106621702,
      productCode: 'P818PTL11',
      productSamples: [
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
      ],
      productGender: 'women',
      productVariable: ['pink', 'Olive', 'Gray', 'Black'],
      productCategory: ['legging'],
      productDescription: {
        prefix: 'Water Absorbable Quick Drying UV',
        availability: 10,
        sizes: ['s', 'm', 'l'],
        sizeSpec: [
          {
            size: 's',
            measure: 'cm',
            spec:
              '[waist] 76.0 [hip] 103.0 [hem opening] 40.2 [pants length] 97.0 [inseam] 78.0',
          },
          {
            size: 'm',
            measure: 'cm',
            spec:
              '[waist] 80.0 [hip] 107.0 [ Hemp mouth] 41.0 [Pants Length] 101.0 [Inseam] 81.0',
          },
          {
            size: 'l',
            measure: 'cm',
            spec:
              '[Waist] 84.0 [Hip] 111.0 [Hemming Port] 41.8 [Pants Length] 105.0 [Inseam] 84.0 ',
          },
        ],
        info: [
          'Parker that can be UV-protected from the sun in summer',
          'Ultraviolet cut is the highest value UPF 50+',
          'Peaks Eight unique fabric is used',
          'Shaw Deodorant effect using yarn',
          'Simple design that since the time of commuting and going out not only the seaside',
        ],
      },
      productName: 'Legging',
      productPrice: 280000,
      listingDate: '04/21/2018',
      location: 'hcm',
    },
    {
      productImg:
        'https://base-ec2if.akamaized.net/w=300,a=0,q=90,u=1/images/item/origin/2c3246a771dca90ed78a57a9a8aeb595.jpg',
      productId: 106621703,
      productCode: 'P818PTL11',
      productSamples: [
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
      ],
      productGender: 'women',
      productVariable: ['pink', 'Olive', 'Gray', 'Black'],
      productCategory: ['legging'],
      productDescription: {
        prefix: 'Water Absorbable Quick Drying UV',
        availability: 10,
        sizes: ['s', 'm', 'l'],
        sizeSpec: [
          {
            size: 's',
            measure: 'cm',
            spec:
              '[waist] 76.0 [hip] 103.0 [hem opening] 40.2 [pants length] 97.0 [inseam] 78.0',
          },
          {
            size: 'm',
            measure: 'cm',
            spec:
              '[waist] 80.0 [hip] 107.0 [ Hemp mouth] 41.0 [Pants Length] 101.0 [Inseam] 81.0',
          },
          {
            size: 'l',
            measure: 'cm',
            spec:
              '[Waist] 84.0 [Hip] 111.0 [Hemming Port] 41.8 [Pants Length] 105.0 [Inseam] 84.0 ',
          },
        ],
        info: [
          'Parker that can be UV-protected from the sun in summer',
          'Ultraviolet cut is the highest value UPF 50+',
          'Peaks Eight unique fabric is used',
          'Shaw Deodorant effect using yarn',
          'Simple design that since the time of commuting and going out not only the seaside',
        ],
      },
      productName: 'Legging',
      productPrice: 280000,
      listingDate: '04/21/2018',
      location: 'hcm',
    },
    {
      productImg:
        'https://base-ec2if.akamaized.net/w=300,a=0,q=90,u=1/images/item/origin/2c3246a771dca90ed78a57a9a8aeb595.jpg',
      productId: 106621704,
      productCode: 'P818PTL11',
      productSamples: [
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
      ],
      productGender: 'women',
      productVariable: ['pink', 'Olive', 'Gray', 'Black'],
      productCategory: ['legging'],
      productDescription: {
        prefix: 'Water Absorbable Quick Drying UV',
        availability: 10,
        sizes: ['s', 'm', 'l'],
        sizeSpec: [
          {
            size: 's',
            measure: 'cm',
            spec:
              '[waist] 76.0 [hip] 103.0 [hem opening] 40.2 [pants length] 97.0 [inseam] 78.0',
          },
          {
            size: 'm',
            measure: 'cm',
            spec:
              '[waist] 80.0 [hip] 107.0 [ Hemp mouth] 41.0 [Pants Length] 101.0 [Inseam] 81.0',
          },
          {
            size: 'l',
            measure: 'cm',
            spec:
              '[Waist] 84.0 [Hip] 111.0 [Hemming Port] 41.8 [Pants Length] 105.0 [Inseam] 84.0 ',
          },
        ],
        info: [
          'Parker that can be UV-protected from the sun in summer',
          'Ultraviolet cut is the highest value UPF 50+',
          'Peaks Eight unique fabric is used',
          'Shaw Deodorant effect using yarn',
          'Simple design that since the time of commuting and going out not only the seaside',
        ],
      },
      productName: 'Legging',
      productPrice: 280000,
      listingDate: '04/21/2018',
      location: 'hcm',
    },
    {
      productImg:
        'https://base-ec2if.akamaized.net/w=300,a=0,q=90,u=1/images/item/origin/2c3246a771dca90ed78a57a9a8aeb595.jpg',
      productId: 106621705,
      productCode: 'P818PTL11',
      productSamples: [
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
      ],
      productGender: 'women',
      productVariable: ['pink', 'Olive', 'Gray', 'Black'],
      productCategory: ['legging'],
      productDescription: {
        prefix: 'Water Absorbable Quick Drying UV',
        availability: 10,
        sizes: ['s', 'm', 'l'],
        sizeSpec: [
          {
            size: 's',
            measure: 'cm',
            spec:
              '[waist] 76.0 [hip] 103.0 [hem opening] 40.2 [pants length] 97.0 [inseam] 78.0',
          },
          {
            size: 'm',
            measure: 'cm',
            spec:
              '[waist] 80.0 [hip] 107.0 [ Hemp mouth] 41.0 [Pants Length] 101.0 [Inseam] 81.0',
          },
          {
            size: 'l',
            measure: 'cm',
            spec:
              '[Waist] 84.0 [Hip] 111.0 [Hemming Port] 41.8 [Pants Length] 105.0 [Inseam] 84.0 ',
          },
        ],
        info: [
          'Parker that can be UV-protected from the sun in summer',
          'Ultraviolet cut is the highest value UPF 50+',
          'Peaks Eight unique fabric is used',
          'Shaw Deodorant effect using yarn',
          'Simple design that since the time of commuting and going out not only the seaside',
        ],
      },
      productName: 'Legging',
      productPrice: 280000,
      listingDate: '04/21/2018',
      location: 'hcm',
    },
    {
      productImg:
        'https://base-ec2if.akamaized.net/w=300,a=0,q=90,u=1/images/item/origin/2c3246a771dca90ed78a57a9a8aeb595.jpg',
      productId: 106621706,
      productCode: 'P818PTL11',
      productSamples: [
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
      ],
      productGender: 'women',
      productVariable: ['pink', 'Olive', 'Gray', 'Black'],
      productCategory: ['legging'],
      productDescription: {
        prefix: 'Water Absorbable Quick Drying UV',
        availability: 10,
        sizes: ['s', 'm', 'l'],
        sizeSpec: [
          {
            size: 's',
            measure: 'cm',
            spec:
              '[waist] 76.0 [hip] 103.0 [hem opening] 40.2 [pants length] 97.0 [inseam] 78.0',
          },
          {
            size: 'm',
            measure: 'cm',
            spec:
              '[waist] 80.0 [hip] 107.0 [ Hemp mouth] 41.0 [Pants Length] 101.0 [Inseam] 81.0',
          },
          {
            size: 'l',
            measure: 'cm',
            spec:
              '[Waist] 84.0 [Hip] 111.0 [Hemming Port] 41.8 [Pants Length] 105.0 [Inseam] 84.0 ',
          },
        ],
        info: [
          'Parker that can be UV-protected from the sun in summer',
          'Ultraviolet cut is the highest value UPF 50+',
          'Peaks Eight unique fabric is used',
          'Shaw Deodorant effect using yarn',
          'Simple design that since the time of commuting and going out not only the seaside',
        ],
      },
      productName: 'Legging',
      productPrice: 280000,
      listingDate: '04/21/2018',
      location: 'hcm',
    },
    {
      productImg:
        'https://base-ec2if.akamaized.net/w=300,a=0,q=90,u=1/images/item/origin/ad7ee701541d4b50a90432851b2eb910.jpg',
      productId: 1066224974,
      productCode: 'P818PTL01',
      productSamples: [
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
      ],
      productGender: 'men',
      productVariable: ['gray', 'olive', 'black'],
      productCategory: ['pants'],
      productDescription: {
        prefix: 'Water Absorbable Quick Drying UV',
        availability: 10,
        sizes: ['s', 'm', 'l'],
        sizeSpec: [
          {
            size: 's',
            measure: 'cm',
            spec:
              '[waist] 76.0 [hip] 103.0 [hem opening] 40.2 [pants length] 97.0 [inseam] 78.0',
          },
          {
            size: 'm',
            measure: 'cm',
            spec:
              '[waist] 80.0 [hip] 107.0 [ Hemp mouth] 41.0 [Pants Length] 101.0 [Inseam] 81.0',
          },
          {
            size: 'l',
            measure: 'cm',
            spec:
              '[Waist] 84.0 [Hip] 111.0 [Hemming Port] 41.8 [Pants Length] 105.0 [Inseam] 84.0 ',
          },
        ],
        info: [
          'Parker that can be UV-protected from the sun in summer',
          'Ultraviolet cut is the highest value UPF 50+',
          'Peaks Eight unique fabric is used',
          'Shaw Deodorant effect using yarn',
          'Simple design that since the time of commuting and going out not only the seaside',
        ],
      },
      productName: 'Long Pants',
      productPrice: 280000,
      listingDate: '04/21/2018',
      location: 'hcm',
    },
    {
      productImg:
        'https://base-ec2if.akamaized.net/w=300,a=0,q=90,u=1/images/item/origin/ad7ee701541d4b50a90432851b2eb910.jpg',
      productId: 1066224986,
      productCode: 'P818PTL01',
      productSamples: [
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
      ],
      productGender: 'men',
      productVariable: ['gray', 'olive', 'black'],
      productCategory: ['pants'],
      productDescription: {
        prefix: 'Water Absorbable Quick Drying UV',
        availability: 10,
        sizes: ['s', 'm', 'l'],
        sizeSpec: [
          {
            size: 's',
            measure: 'cm',
            spec:
              '[waist] 76.0 [hip] 103.0 [hem opening] 40.2 [pants length] 97.0 [inseam] 78.0',
          },
          {
            size: 'm',
            measure: 'cm',
            spec:
              '[waist] 80.0 [hip] 107.0 [ Hemp mouth] 41.0 [Pants Length] 101.0 [Inseam] 81.0',
          },
          {
            size: 'l',
            measure: 'cm',
            spec:
              '[Waist] 84.0 [Hip] 111.0 [Hemming Port] 41.8 [Pants Length] 105.0 [Inseam] 84.0 ',
          },
        ],
        info: [
          'Parker that can be UV-protected from the sun in summer',
          'Ultraviolet cut is the highest value UPF 50+',
          'Peaks Eight unique fabric is used',
          'Shaw Deodorant effect using yarn',
          'Simple design that since the time of commuting and going out not only the seaside',
        ],
      },
      productName: 'Long Pants',
      productPrice: 280000,
      listingDate: '04/21/2018',
      location: 'hcm',
    },
    {
      productImg:
        'https://base-ec2if.akamaized.net/w=300,a=0,q=90,u=1/images/item/origin/ad7ee701541d4b50a90432851b2eb910.jpg',
      productId: 106622499,
      productCode: 'P818PTL01',
      productSamples: [
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
      ],
      productGender: 'men',
      productVariable: ['gray', 'olive', 'black'],
      productCategory: ['pants'],
      productDescription: {
        prefix: 'Water Absorbable Quick Drying UV',
        availability: 10,
        sizes: ['s', 'm', 'l'],
        sizeSpec: [
          {
            size: 's',
            measure: 'cm',
            spec:
              '[waist] 76.0 [hip] 103.0 [hem opening] 40.2 [pants length] 97.0 [inseam] 78.0',
          },
          {
            size: 'm',
            measure: 'cm',
            spec:
              '[waist] 80.0 [hip] 107.0 [ Hemp mouth] 41.0 [Pants Length] 101.0 [Inseam] 81.0',
          },
          {
            size: 'l',
            measure: 'cm',
            spec:
              '[Waist] 84.0 [Hip] 111.0 [Hemming Port] 41.8 [Pants Length] 105.0 [Inseam] 84.0 ',
          },
        ],
        info: [
          'Parker that can be UV-protected from the sun in summer',
          'Ultraviolet cut is the highest value UPF 50+',
          'Peaks Eight unique fabric is used',
          'Shaw Deodorant effect using yarn',
          'Simple design that since the time of commuting and going out not only the seaside',
        ],
      },
      productName: 'Long Pants',
      productPrice: 280000,
      listingDate: '04/21/2018',
      location: 'hcm',
    },
    {
      productImg:
        'https://base-ec2if.akamaized.net/w=300,a=0,q=90,u=1/images/item/origin/ad7ee701541d4b50a90432851b2eb910.jpg',
      productId: 106622498,
      productCode: 'P818PTL01',
      productSamples: [
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
      ],
      productGender: 'men',
      productVariable: ['gray', 'olive', 'black'],
      productCategory: ['pants'],
      productDescription: {
        prefix: 'Water Absorbable Quick Drying UV',
        availability: 10,
        sizes: ['s', 'm', 'l'],
        sizeSpec: [
          {
            size: 's',
            measure: 'cm',
            spec:
              '[waist] 76.0 [hip] 103.0 [hem opening] 40.2 [pants length] 97.0 [inseam] 78.0',
          },
          {
            size: 'm',
            measure: 'cm',
            spec:
              '[waist] 80.0 [hip] 107.0 [ Hemp mouth] 41.0 [Pants Length] 101.0 [Inseam] 81.0',
          },
          {
            size: 'l',
            measure: 'cm',
            spec:
              '[Waist] 84.0 [Hip] 111.0 [Hemming Port] 41.8 [Pants Length] 105.0 [Inseam] 84.0 ',
          },
        ],
        info: [
          'Parker that can be UV-protected from the sun in summer',
          'Ultraviolet cut is the highest value UPF 50+',
          'Peaks Eight unique fabric is used',
          'Shaw Deodorant effect using yarn',
          'Simple design that since the time of commuting and going out not only the seaside',
        ],
      },
      productName: 'Long Pants',
      productPrice: 280000,
      listingDate: '04/21/2018',
      location: 'hcm',
    },
    {
      productImg:
        'https://base-ec2if.akamaized.net/w=300,a=0,q=90,u=1/images/item/origin/ad7ee701541d4b50a90432851b2eb910.jpg',
      productId: 106622497,
      productCode: 'P818PTL01',
      productSamples: [
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
      ],
      productGender: 'men',
      productVariable: ['gray', 'olive', 'black'],
      productCategory: ['pants'],
      productDescription: {
        prefix: 'Water Absorbable Quick Drying UV',
        availability: 10,
        sizes: ['s', 'm', 'l'],
        sizeSpec: [
          {
            size: 's',
            measure: 'cm',
            spec:
              '[waist] 76.0 [hip] 103.0 [hem opening] 40.2 [pants length] 97.0 [inseam] 78.0',
          },
          {
            size: 'm',
            measure: 'cm',
            spec:
              '[waist] 80.0 [hip] 107.0 [ Hemp mouth] 41.0 [Pants Length] 101.0 [Inseam] 81.0',
          },
          {
            size: 'l',
            measure: 'cm',
            spec:
              '[Waist] 84.0 [Hip] 111.0 [Hemming Port] 41.8 [Pants Length] 105.0 [Inseam] 84.0 ',
          },
        ],
        info: [
          'Parker that can be UV-protected from the sun in summer',
          'Ultraviolet cut is the highest value UPF 50+',
          'Peaks Eight unique fabric is used',
          'Shaw Deodorant effect using yarn',
          'Simple design that since the time of commuting and going out not only the seaside',
        ],
      },
      productName: 'Long Pants',
      productPrice: 280000,
      listingDate: '04/21/2018',
      location: 'hcm',
    },
    {
      productImg:
        'https://base-ec2if.akamaized.net/w=300,a=0,q=90,u=1/images/item/origin/07ba182542474b8325afdf845ebaacd2.jpg',
      productId: 106610536,
      productCode: 'P818PTM01',
      productSamples: [
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
        'https://base-ec2if.akamaized.net/images/item/origin/1f0948740d9a03e91f10007415ab88ae.jpg',
      ],
      productGender: 'men',
      productVariable: ['olive', 'gray', 'black'],
      productCategory: ['pants'],
      productDescription: {
        prefix: 'Water Absorbable Quick Drying UV',
        availability: 10,
        sizes: ['s', 'm', 'l'],
        sizeSpec: [
          {
            size: 's',
            measure: 'cm',
            spec:
              '[waist] 76.0 [hip] 103.0 [hem opening] 40.2 [pants length] 97.0 [inseam] 78.0',
          },
          {
            size: 'm',
            measure: 'cm',
            spec:
              '[waist] 80.0 [hip] 107.0 [ Hemp mouth] 41.0 [Pants Length] 101.0 [Inseam] 81.0',
          },
          {
            size: 'l',
            measure: 'cm',
            spec:
              '[Waist] 84.0 [Hip] 111.0 [Hemming Port] 41.8 [Pants Length] 105.0 [Inseam] 84.0 ',
          },
        ],
        info: [
          'Parker that can be UV-protected from the sun in summer',
          'Ultraviolet cut is the highest value UPF 50+',
          'Peaks Eight unique fabric is used',
          'Shaw Deodorant effect using yarn',
          'Simple design that since the time of commuting and going out not only the seaside',
        ],
      },
      productName: 'Long Pants',
      productPrice: 280000,
      listingDate: '04/21/2018',
      location: 'hcm',
    },
  ],
  pickUpData: [
    {
      imgLink:
        'https://base-ec2if.akamaized.net/images/user/template/peaks8-official-ec/image-pick_img_1_5ac6ea2d6a80d.jpg',
      imgDescription: 'Facebook',
      title: 'facebook',
      description: 'We opened official Facebook page of "Peaks Eight"!',
      metalink: 'https://www.facebook.com/PeaksEight',
    },
    {
      imgLink:
        'https://base-ec2if.akamaized.net/images/user/template/peaks8-official-ec/image-pick_img_2_5ac6ea2db16b6.jpg',
      imgDescription: 'Twitter',
      title: 'twitter',
      description: 'We opened official Twitter page of "Peaks Eight"!',
      metalink: 'https://twitter.com/peaks_eight',
    },
    {
      imgLink:
        'https://base-ec2if.akamaized.net/images/user/template/peaks8-official-ec/image-pick_img_3_5ac6ea2e08c29.jpg',
      imgDescription: 'Instagram',
      title: 'instagram',
      description: 'We opened official Instagram page of "Peaks Eight"!',
      metalink: 'https://www.instagram.com/peaks_eight',
    },
  ],
  navBar: [
    {
      id: 1,
      title: 'home',
      url: '/',
    },
    {
      id: 2,
      title: 'about',
      url: '/about',
    },
    {
      id: 3,
      title: 'category',
      url: '/category',
    },
    {
      id: 4,
      title: 'contact',
      url: '/contact',
    },
  ],
  usersData: [
    {
      userId: 1,
      userName: 'daniel',
      password: 'danielrace',
      name: 'Test Name',
      address: 'Test Address',
      phone: '8123',
      email: '123@123.com',
      paymentMethods: ['credit card', 'cod'],
      purchasedItems: [
        {
          itemCode: '12341251',
          orderDate: '12/5/2018',
          orderStatus: 'paid',
          additionalInfo: '',
          details: [
            {
              size: 's',
              color: 'grey',
              quantity: 1,
            },
            {
              size: 'l',
              color: 'black',
              quantity: 1,
            },
          ],
        },
        {
          itemCode: '123412531',
          orderDate: '12/5/2018',
          orderStatus: 'unpaid',
          additionalInfo: '',
          details: [
            {
              size: 'l',
              color: 'grey',
              quantity: 5,
            },
          ],
        },
      ],
      cartItems: [
        {
          itemCode: '123234351',
          size: 'l',
          color: 'grey',
          quantity: 5,
        },
      ],
      isAdmin: true,
      registerDate: '',
    },
  ],
};
export const fakeOrders = [
  {
    orderDate: '2017-12-24T02:13:20.109Z',
    orderId: 98594,
    orderName: 'Vũ Đào',
    orderAddress: 'Apt. 393',
    orderPhone: '01723 79342',
    orderTotalPrice: '750.00',
    orderPaymentType: 'invoice',
    orderItems: [
      {
        itemId: 73770,
        itemCode: 'Ergonomic',
        itemName: 'Refined Cotton Tuna',
        itemCategory: 'Health',
        itemColor: 'fuchsia',
        itemQuantity: 54527,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '965.00',
      },
      {
        itemId: 25264,
        itemCode: 'Gorgeous',
        itemName: 'Awesome Steel Fish',
        itemCategory: 'Health',
        itemColor: 'silver',
        itemQuantity: 2597,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '149.00',
      },
      {
        itemId: 56957,
        itemCode: 'Sleek',
        itemName: 'Practical Plastic Sausages',
        itemCategory: 'Garden',
        itemColor: 'purple',
        itemQuantity: 68789,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '850.00',
      },
    ],
  },
  {
    orderDate: '2018-03-15T15:56:24.230Z',
    orderId: 86060,
    orderName: 'Mai Hà DDS',
    orderAddress: 'Apt. 156',
    orderPhone: '055 5046 4835',
    orderTotalPrice: '447.00',
    orderPaymentType: 'withdrawal',
    orderItems: [
      {
        itemId: 971,
        itemCode: 'Handmade',
        itemName: 'Gorgeous Concrete Mouse',
        itemCategory: 'Health',
        itemColor: 'red',
        itemQuantity: 52960,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '447.00',
      },
      {
        itemId: 44998,
        itemCode: 'Gorgeous',
        itemName: 'Unbranded Granite Soap',
        itemCategory: 'Books',
        itemColor: 'tan',
        itemQuantity: 5017,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '852.00',
      },
      {
        itemId: 22643,
        itemCode: 'Gorgeous',
        itemName: 'Intelligent Metal Chair',
        itemCategory: 'Clothing',
        itemColor: 'ivory',
        itemQuantity: 64407,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '554.00',
      },
    ],
  },
  {
    orderDate: '2017-05-21T12:18:23.475Z',
    orderId: 86493,
    orderName: 'Tăng Bùi II',
    orderAddress: 'Suite 604',
    orderPhone: '0999 716 6450',
    orderTotalPrice: '94.00',
    orderPaymentType: 'deposit',
    orderItems: [
      {
        itemId: 29471,
        itemCode: 'Practical',
        itemName: 'Sleek Granite Bacon',
        itemCategory: 'Games',
        itemColor: 'green',
        itemQuantity: 81361,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '996.00',
      },
      {
        itemId: 45642,
        itemCode: 'Generic',
        itemName: 'Licensed Plastic Bacon',
        itemCategory: 'Toys',
        itemColor: 'pink',
        itemQuantity: 52804,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '558.00',
      },
      {
        itemId: 84983,
        itemCode: 'Handmade',
        itemName: 'Sleek Rubber Bacon',
        itemCategory: 'Outdoors',
        itemColor: 'teal',
        itemQuantity: 88789,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '895.00',
      },
    ],
  },
  {
    orderDate: '2017-10-31T04:06:51.167Z',
    orderId: 71442,
    orderName: 'Đào Thắgn',
    orderAddress: 'Suite 679',
    orderPhone: '023 6971 4807',
    orderTotalPrice: '986.00',
    orderPaymentType: 'withdrawal',
    orderItems: [
      {
        itemId: 15197,
        itemCode: 'Incredible',
        itemName: 'Licensed Cotton Cheese',
        itemCategory: 'Outdoors',
        itemColor: 'teal',
        itemQuantity: 99892,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '107.00',
      },
      {
        itemId: 41811,
        itemCode: 'Ergonomic',
        itemName: 'Refined Steel Chips',
        itemCategory: 'Beauty',
        itemColor: 'green',
        itemQuantity: 58361,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '534.00',
      },
      {
        itemId: 25248,
        itemCode: 'Handcrafted',
        itemName: 'Handcrafted Fresh Soap',
        itemCategory: 'Baby',
        itemColor: 'fuchsia',
        itemQuantity: 6060,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '814.00',
      },
    ],
  },
  {
    orderDate: '2017-06-13T10:04:28.128Z',
    orderId: 59292,
    orderName: 'Tô Ngô',
    orderAddress: 'Apt. 916',
    orderPhone: '0800 668 8645',
    orderTotalPrice: '826.00',
    orderPaymentType: 'deposit',
    orderItems: [
      {
        itemId: 65378,
        itemCode: 'Refined',
        itemName: 'Handcrafted Steel Chicken',
        itemCategory: 'Music',
        itemColor: 'yellow',
        itemQuantity: 47296,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '786.00',
      },
      {
        itemId: 52841,
        itemCode: 'Awesome',
        itemName: 'Handmade Frozen Car',
        itemCategory: 'Garden',
        itemColor: 'salmon',
        itemQuantity: 84053,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '222.00',
      },
      {
        itemId: 77051,
        itemCode: 'Tasty',
        itemName: 'Handmade Steel Car',
        itemCategory: 'Electronics',
        itemColor: 'turquoise',
        itemQuantity: 94302,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '597.00',
      },
    ],
  },
  {
    orderDate: '2017-12-20T20:46:29.975Z',
    orderId: 18503,
    orderName: 'Đoàn Thị',
    orderAddress: 'Suite 054',
    orderPhone: '016977 4992',
    orderTotalPrice: '290.00',
    orderPaymentType: 'invoice',
    orderItems: [
      {
        itemId: 40220,
        itemCode: 'Refined',
        itemName: 'Gorgeous Plastic Shirt',
        itemCategory: 'Shoes',
        itemColor: 'ivory',
        itemQuantity: 54418,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '764.00',
      },
      {
        itemId: 94888,
        itemCode: 'Handmade',
        itemName: 'Sleek Frozen Hat',
        itemCategory: 'Movies',
        itemColor: 'tan',
        itemQuantity: 34214,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '607.00',
      },
      {
        itemId: 81098,
        itemCode: 'Generic',
        itemName: 'Handcrafted Steel Fish',
        itemCategory: 'Clothing',
        itemColor: 'plum',
        itemQuantity: 52397,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '979.00',
      },
    ],
  },
  {
    orderDate: '2017-06-22T11:46:16.367Z',
    orderId: 7472,
    orderName: 'Tăng Lâm',
    orderAddress: 'Apt. 426',
    orderPhone: '0800 358716',
    orderTotalPrice: '622.00',
    orderPaymentType: 'withdrawal',
    orderItems: [
      {
        itemId: 50226,
        itemCode: 'Unbranded',
        itemName: 'Awesome Fresh Bacon',
        itemCategory: 'Games',
        itemColor: 'magenta',
        itemQuantity: 4563,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '110.00',
      },
      {
        itemId: 15100,
        itemCode: 'Unbranded',
        itemName: 'Generic Granite Computer',
        itemCategory: 'Electronics',
        itemColor: 'sky blue',
        itemQuantity: 13110,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '651.00',
      },
      {
        itemId: 68043,
        itemCode: 'Unbranded',
        itemName: 'Fantastic Soft Bacon',
        itemCategory: 'Industrial',
        itemColor: 'mint green',
        itemQuantity: 19081,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '569.00',
      },
    ],
  },
  {
    orderDate: '2017-06-17T23:16:11.710Z',
    orderId: 54954,
    orderName: 'Ngô Hòa',
    orderAddress: 'Suite 753',
    orderPhone: '0980 077 5002',
    orderTotalPrice: '36.00',
    orderPaymentType: 'payment',
    orderItems: [
      {
        itemId: 54608,
        itemCode: 'Practical',
        itemName: 'Handcrafted Concrete Sausages',
        itemCategory: 'Games',
        itemColor: 'turquoise',
        itemQuantity: 75487,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '948.00',
      },
      {
        itemId: 79933,
        itemCode: 'Unbranded',
        itemName: 'Sleek Steel Computer',
        itemCategory: 'Beauty',
        itemColor: 'pink',
        itemQuantity: 16970,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '805.00',
      },
      {
        itemId: 36078,
        itemCode: 'Fantastic',
        itemName: 'Incredible Frozen Ball',
        itemCategory: 'Tools',
        itemColor: 'tan',
        itemQuantity: 99978,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '299.00',
      },
    ],
  },
  {
    orderDate: '2018-04-02T07:56:39.427Z',
    orderId: 94852,
    orderName: 'Đinh Sơn',
    orderAddress: 'Suite 758',
    orderPhone: '0916 569 5200',
    orderTotalPrice: '586.00',
    orderPaymentType: 'invoice',
    orderItems: [
      {
        itemId: 35891,
        itemCode: 'Tasty',
        itemName: 'Handcrafted Granite Ball',
        itemCategory: 'Outdoors',
        itemColor: 'lavender',
        itemQuantity: 26951,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '974.00',
      },
      {
        itemId: 53729,
        itemCode: 'Sleek',
        itemName: 'Awesome Cotton Shoes',
        itemCategory: 'Garden',
        itemColor: 'mint green',
        itemQuantity: 79695,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '930.00',
      },
      {
        itemId: 88842,
        itemCode: 'Rustic',
        itemName: 'Practical Concrete Pizza',
        itemCategory: 'Music',
        itemColor: 'mint green',
        itemQuantity: 96546,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '43.00',
      },
    ],
  },
  {
    orderDate: '2017-08-16T21:32:01.825Z',
    orderId: 36815,
    orderName: 'Lý Hòa',
    orderAddress: 'Suite 095',
    orderPhone: '017589 09004',
    orderTotalPrice: '523.00',
    orderPaymentType: 'withdrawal',
    orderItems: [
      {
        itemId: 82963,
        itemCode: 'Handmade',
        itemName: 'Small Concrete Towels',
        itemCategory: 'Clothing',
        itemColor: 'azure',
        itemQuantity: 39577,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '305.00',
      },
      {
        itemId: 13875,
        itemCode: 'Gorgeous',
        itemName: 'Fantastic Granite Salad',
        itemCategory: 'Automotive',
        itemColor: 'teal',
        itemQuantity: 92233,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '878.00',
      },
      {
        itemId: 21917,
        itemCode: 'Unbranded',
        itemName: 'Handcrafted Concrete Chips',
        itemCategory: 'Toys',
        itemColor: 'maroon',
        itemQuantity: 11077,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '93.00',
      },
    ],
  },
  {
    orderDate: '2017-07-15T03:30:10.560Z',
    orderId: 44832,
    orderName: 'Phan Lê',
    orderAddress: 'Apt. 503',
    orderPhone: '0800 468 3222',
    orderTotalPrice: '692.00',
    orderPaymentType: 'payment',
    orderItems: [
      {
        itemId: 92627,
        itemCode: 'Awesome',
        itemName: 'Unbranded Granite Table',
        itemCategory: 'Home',
        itemColor: 'purple',
        itemQuantity: 12321,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '320.00',
      },
      {
        itemId: 89864,
        itemCode: 'Gorgeous',
        itemName: 'Incredible Plastic Gloves',
        itemCategory: 'Jewelery',
        itemColor: 'tan',
        itemQuantity: 37937,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '193.00',
      },
      {
        itemId: 71914,
        itemCode: 'Intelligent',
        itemName: 'Practical Fresh Ball',
        itemCategory: 'Garden',
        itemColor: 'indigo',
        itemQuantity: 96015,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '783.00',
      },
    ],
  },
  {
    orderDate: '2017-08-20T09:19:08.235Z',
    orderId: 31875,
    orderName: 'Hoàng Sinh',
    orderAddress: 'Suite 114',
    orderPhone: '016977 6390',
    orderTotalPrice: '549.00',
    orderPaymentType: 'payment',
    orderItems: [
      {
        itemId: 14145,
        itemCode: 'Practical',
        itemName: 'Practical Frozen Shirt',
        itemCategory: 'Tools',
        itemColor: 'orchid',
        itemQuantity: 46251,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '694.00',
      },
      {
        itemId: 12337,
        itemCode: 'Sleek',
        itemName: 'Small Metal Bacon',
        itemCategory: 'Baby',
        itemColor: 'salmon',
        itemQuantity: 11720,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '999.00',
      },
      {
        itemId: 77145,
        itemCode: 'Intelligent',
        itemName: 'Handmade Metal Cheese',
        itemCategory: 'Industrial',
        itemColor: 'green',
        itemQuantity: 36889,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '622.00',
      },
    ],
  },
  {
    orderDate: '2017-10-09T04:45:31.027Z',
    orderId: 76431,
    orderName: 'Phùng Hữu',
    orderAddress: 'Suite 457',
    orderPhone: '0800 661 9086',
    orderTotalPrice: '647.00',
    orderPaymentType: 'payment',
    orderItems: [
      {
        itemId: 94888,
        itemCode: 'Handcrafted',
        itemName: 'Handmade Frozen Computer',
        itemCategory: 'Beauty',
        itemColor: 'red',
        itemQuantity: 6706,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '379.00',
      },
      {
        itemId: 64582,
        itemCode: 'Unbranded',
        itemName: 'Awesome Fresh Table',
        itemCategory: 'Clothing',
        itemColor: 'turquoise',
        itemQuantity: 14301,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '545.00',
      },
      {
        itemId: 75309,
        itemCode: 'Handmade',
        itemName: 'Licensed Granite Fish',
        itemCategory: 'Beauty',
        itemColor: 'turquoise',
        itemQuantity: 13360,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '209.00',
      },
    ],
  },
  {
    orderDate: '2017-09-04T21:09:32.910Z',
    orderId: 85147,
    orderName: 'Mr. Dương Nguyễn',
    orderAddress: 'Apt. 974',
    orderPhone: '0500 114577',
    orderTotalPrice: '7.00',
    orderPaymentType: 'deposit',
    orderItems: [
      {
        itemId: 217,
        itemCode: 'Intelligent',
        itemName: 'Rustic Frozen Salad',
        itemCategory: 'Clothing',
        itemColor: 'teal',
        itemQuantity: 20299,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '96.00',
      },
      {
        itemId: 10521,
        itemCode: 'Small',
        itemName: 'Awesome Cotton Shoes',
        itemCategory: 'Clothing',
        itemColor: 'cyan',
        itemQuantity: 55728,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '88.00',
      },
      {
        itemId: 2161,
        itemCode: 'Practical',
        itemName: 'Fantastic Cotton Tuna',
        itemCategory: 'Tools',
        itemColor: 'orange',
        itemQuantity: 77750,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '427.00',
      },
    ],
  },
  {
    orderDate: '2018-04-08T15:30:23.379Z',
    orderId: 30259,
    orderName: 'Đinh Nhân',
    orderAddress: 'Apt. 837',
    orderPhone: '0346 771 9981',
    orderTotalPrice: '165.00',
    orderPaymentType: 'invoice',
    orderItems: [
      {
        itemId: 37055,
        itemCode: 'Intelligent',
        itemName: 'Rustic Plastic Tuna',
        itemCategory: 'Movies',
        itemColor: 'teal',
        itemQuantity: 1566,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '934.00',
      },
      {
        itemId: 67133,
        itemCode: 'Unbranded',
        itemName: 'Rustic Fresh Salad',
        itemCategory: 'Tools',
        itemColor: 'sky blue',
        itemQuantity: 19866,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '906.00',
      },
      {
        itemId: 83389,
        itemCode: 'Incredible',
        itemName: 'Handcrafted Concrete Bike',
        itemCategory: 'Grocery',
        itemColor: 'mint green',
        itemQuantity: 1401,
        itemImg: 'http://lorempixel.com/640/480',
        itemPrice: '663.00',
      },
    ],
  },
];

export default data;
